obj-m := enoki_shinjuku.o
enoki_shinjuku-objs := src/module.o enoki_shinjuku.rust.o

EXTRA_LDFLAGS += --entry=init_module --undefined=cleanup_module

CARGO ?= cargo

export c_flags

$(src)/target/x86_64-unknown-none-linuxkernel/release/libenoki_shinjuku.a: $(src)/Cargo.toml $(wildcard $(src)/src/*.rs)
	cd $(src); env -u MAKE -u MAKEFLAGS $(CARGO) build -Z build-std=core,alloc --release --target=x86_64-unknown-none-linuxkernel

%.rust.o: target/x86_64-unknown-none-linuxkernel/release/lib%.a
	$(LD) -r -o $@ --whole-archive $<
